config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :links
    resources :shows
    resources :products
    resources :categories
    resources :background_images
  end
  devise_for :admins

  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end
  end

  resources :shows

  resources :links

  resources :carts, param: :secret_id, only: [:create, :show]

  resources :cart_items, only: [:destroy]

  resource :background_images, only: [:show, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do 
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show, :index]

  get "admin" => "admin#index"

  post 'checkout', to: 'checkouts#create', as: 'cart_checkout'
  get 'checkout/success', to: 'checkouts#success'
  get 'checkout/cancel', to: 'checkouts#cancel'

  get 'checkout', to: 'checkouts#show', as: 'checkout'
  post 'checkout/create', to: 'checkouts#create'

end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :products, through: :cart_items

    before_create :set_secret_id

    private

    def set_secret_id 
        self.secret_id = SecureRandom.uuid
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def create 
        @product = Product.find(params[:product_id])
        selected_option = params[:selected_option]

        @current_cart.cart_items.find_or_create_by(product: @product) do |item|
          item.update(options: selected_option) if selected_option.present?

          respond_to do |format|
            redirect_to cart_path(@current_cart.secret_id)
            format.turbo_stream
          end

        end

    
        # respond_to do |format|
        #   format.turbo_stream 
        #   format.html { redirect_to products_path, notice: "#{product.name} added to cart" }
        # end
    end 

    def show
        @cart = Cart.find_by(secret_id: params[:secret_id])
        if @cart
          @cart_id = @cart.id
          @cart_items = @cart.cart_items.includes(:product)
        else
          render plain: "Cart not found", status: :not_found
        end
        
      end
end

app/views/carts/_cart_item.html.erb
<div id="<%= dom_id(cart_item) %>" class="mb-4 lg:px-0 px-2 flex items-center border border-gray-400 justify-around">
    <%= image_tag product.images.last, class: "w-16 h-16 lg:m-0 mr-2 object-cover" if product.images.any?  %>
    <%= link_to "#{product.name}  #{cart_item.options.present? ? cart_item.options : ''}", product_path(product), class: "py-2 w-1/3" %>
    <p class="w-1/3"> <%= number_to_currency product.price %> </p>
    <%= button_to "Remove", cart_item_path(cart_item), method: :delete, 
                 class: "w-1/3 text-red-400 bg-transparent border-none cursor-pointer", data: {turbo: "false"} %>
</div>

app/views/carts/_cart_view.html.erb
<div id="cart_show" class="bg-white w-full flex flex-col p-4 lg:p-12 rounded">
    <h2 class="text-3xl mb-4" >Your Cart</h2>
    <div class="flex flex-col">  
        <% @cart_items.each do |cart_item| %>
        <%= render partial: "carts/cart_item", locals: { cart_item: cart_item,product: cart_item.product } %>
        <% end %>
    </div>
    <p class="mb-4 text-2xl">Cart Total: <%= number_to_currency(@cart_items.sum { |item| item.product.price }) %></p>

    <% unless @cart_items.empty? %>
        <%= button_to "Checkout", checkout_create_path(secret_id: @cart.secret_id), method: :post, data: { controller: "stripe-checkout", stripe_checkout_url_value: checkout_path, turbo: false }, class: "p-2 w-fit bg-blue-600 mb-4 text-white rounded cursor-pointer" %>
    <% else %>
        <button class="p-2 w-fit bg-gray-400 mb-4 text-white rounded opacity-50 cursor-not-allowed" disabled>
        Checkout
    </button>
<% end %>

    <%= link_to "Back to Store", categories_path, class: "p-2 w-fit bg-gray-600 text-white rounded" %>

    <% if notice.present? %>
        <p class="py-2 w-fit px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

</div>

app/views/carts/create.turbo_stream.erb
<%= turbo_stream.replace "cart_navbar", partial: "shared/navbar", locals: { cart: @cart } %>


<turbo-stream action="replace" target="<%= dom_id(@product, :add_to_cart) %>">
  <template>
    <div id="<%= dom_id(@product, :add_to_cart) %>">
      <h2 class="mb-2">Item in Cart!</h2>
      <%= link_to "View Cart", cart_path(@current_cart.secret_id), class: "bg-slate-400 text-black px-4 py-2 mt-4 w-fit rounded cursor-pointer" %>
    </div>
  </template>
</turbo-stream>

<turbo-stream action="remove" target="<%= dom_id(@product, :options) %>"></turbo-stream>

app/views/carts/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@cart_item) %>
<%= turbo_stream.replace "cart_navbar", partial: "shared/navbar", locals: { cart: @cart } %>
<%= turbo_stream.replace "cart_show", partial: "carts/cart_view", locals: { cart: @cart } %>

app/views/carts/show.html.erb
<div class="w-full lg:mx-24"> 
   <%= render partial: "cart_view", locals: { cart: @cart } %>
</div>