config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :links
    resources :shows
    resources :products
    resources :categories
    resources :background_images
  end
  devise_for :admins

  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end
  end

  resources :shows

  resources :links

  resources :carts, param: :secret_id, only: [:create, :show]

  resources :cart_items, only: [:destroy]

  resource :background_images, only: [:show, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do 
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show, :index]

  get "admin" => "admin#index"

  post 'checkout', to: 'checkouts#create', as: 'cart_checkout'
  get 'checkout/success', to: 'checkouts#success'
  get 'checkout/cancel', to: 'checkouts#cancel'

  get 'checkout', to: 'checkouts#show', as: 'checkout'
  post 'checkout/create', to: 'checkouts#create'

end

app/models/product.rb
class Product < ApplicationRecord
    has_many_attached :images
    belongs_to :category
    has_rich_text :description

    store :options, accessors: [:size_options, :format_options], coder: JSON

    before_destroy :delete_images_from_s3, prepend: true

    private

    def delete_images_from_s3
      images.each(&:purge) if images.attached?
    end
  end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    @admin_products = Product.all
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
    @admin_products = Product.find(params[:id])
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Product.find(params[:id])
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_products_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])
    if @admin_product.update(admin_product_params.reject { |k| k["images"]})
      if admin_product_params["images"]
        admin_product_params["images"].each do |image|
          @admin_product.images.attach(image)
        end 
      end
      redirect_to admin_products_path, notice: "Product updated successfully."
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.expect(product: [ :name, :description, :price, :category_id, :active, images: [], size_options: [], format_options: [], ])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController 
   
    def show 
        @product = Product.find(params[:id])  # Corrected variable name
        unless @product.active?
            redirect_to categories_path, alert: "Product not available."
        end
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product], class: "contents") do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul class="list-disc ml-6">
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, rows: 4, class: "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full" %>
    <div class="flex gap-4 mt-2">  
    <% if admin_product.images.any? %>
      <% admin_product.images.each do |image| %>
        <%= image_tag image, class: "w-36 h-36 object-cover" %>
      <% end %>
    <% end %>
    </div>
  </div>

  <div class="flex items-center gap-8">  
    <div class="my-5">
      <%= form.label :price %>
      <%= form.text_field :price, class: "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-2 flex flex-col">
        <%= form.label :category_id, "Category" %>
        <%= form.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name', admin_product.category_id), { include_blank: true }, class: "block shadow rounded-md border bg-white outline-none text-black focus:outline-blue-600 px-3 py-2 mt-2" %>
    </div>

    <div class="my-5">
      <%= form.label :active %>
      <%= form.checkbox :active, class: "block shadow-sm rounded-md border outline-hidden mt-2 h-5 w-5" %>
    </div>
  </div>

  <% if (admin_product.category&.name == "T-Shirts") %>
    <div class="my-5">
      <%= form.label :size_options, "Size Options" %>
      <% ["S", "M", "L"].each do |size| %>
        <div>
          <%= form.check_box :size_options, { multiple: true }, size, nil %> <%= size %>
        </div>
      <% end %>
    </div>
  <% elsif (admin_product.category&.name == "Albums") %>
    <div class="my-5">
      <%= form.label :format_options, "Format Options" %>
      <% ["Vinyl", "Cassette", "Digital"].each do |format| %>
        <div>
          <%= form.check_box :format_options, { multiple: true }, format, nil %> <%= format %>
        </div>
      <% end %>
    </div>
  <% else %>
      <div>  </div>
  <% end %>

  

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= product.description %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product.price %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= product.category_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Active:</strong>
    <%= product.active %>
  </p>
</div>

app/views/admin/products/edit.html.erb
<% content_for :title, "Editing product" %>

<div class="md:w-2/3 w-full p-4">
  <h1 class="font-bold text-3xl">Editing <%= @admin_product.name %></h1>

  <%= render "form", admin_product: @admin_product %>
  
</div>

app/views/admin/products/index.html.erb
<% content_for :title, "Products" %>

<div class="w-full p-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex w-1/2 justify-between items-center">
    <h2 class="font-bold text-3xl">Products</h2>
    <%= link_to "New Product", new_admin_product_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="admin_products" class="w-full">
  <% if @admin_products.any? %>
    <% @admin_products.group_by(&:category).each do |category, products| %>
      <h2 class="text-xl font-bold mt-8 mb-4"><%= category.name %></h2>
      <table class="min-w-full border-collapse border border-gray-300 mb-8">
        <thead>
          <tr class="bg-gray-200">
            <th class="border border-gray-300  px-4 py-2">Name</th>
            <th class="border border-gray-300  px-4 py-2">Active</th>
            <th class="border border-gray-300  px-4 py-2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% products.each do |product| %>
            <tr class="hover:bg-gray-100">
              <td class="border flex items-center border-gray-300 px-4 py-2">
                <div class="h-12 w-12 object-cover mr-4">
                  <%= product.images.any? ? image_tag(product.images.first) : image_tag("https://media.istockphoto.com/id/1147544807/vector/thumbnail-image-vector-graphic.jpg?s=612x612&w=0&k=20&c=rnCKVbdxqkjlcs3xH87-9gocETqpspHFXu5dIGB4wuM=") %>
                </div>
                <%= product.name %>
              </td>
              <td class="border border-gray-300 px-4 py-2"><%= product.active ? "Yes" : "No" %></td>
              <td  class="border border-gray-300 px-4 py-2">
                <div class="flex  h-full items-center px-4 py-2">
                <%= link_to 'Edit', edit_admin_product_path(product), class: "text-blue-500 mr-4 hover:underline" %>
                <%= button_to 'Delete', [:admin, product], method: :delete, data: { confirm: "Are you sure?" }, class: " text-red-500 hover:underline" %> 
                <%=link_to "View", product_path(product), class: "bg-gray-200 py-1 px-3 ml-4 rounded" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% else %>
    <p class="text-center my-10">No products found.</p>
  <% end %>
</div>

</div>

app/views/admin/products/new.html.erb
<% content_for :title, "New product" %>

<div class="md:w-2/3 w-full p-4">
  <h1 class="font-bold text-3xl">New product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<% content_for :title, "Showing product" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing product</h1>

  <%= render @admin_product %>

  <%= link_to "Edit this product", edit_admin_product_path(@admin_product), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this product", @admin_product, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>